export default function Head() {
  return (
    <>
      <title>PvP Match 3 RPG in Solana</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  )
}
